# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\plotting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(564, 562)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.slider_layer = QtWidgets.QSlider(Dialog)
        self.slider_layer.setOrientation(QtCore.Qt.Vertical)
        self.slider_layer.setObjectName("slider_layer")
        self.gridLayout.addWidget(self.slider_layer, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.but_layer_plus = QtWidgets.QPushButton(Dialog)
        self.but_layer_plus.setMaximumSize(QtCore.QSize(20, 16777215))
        self.but_layer_plus.setObjectName("but_layer_plus")
        self.gridLayout.addWidget(self.but_layer_plus, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(30, 50))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.txt_curr_layer = QtWidgets.QLineEdit(Dialog)
        self.txt_curr_layer.setMaximumSize(QtCore.QSize(40, 16777215))
        self.txt_curr_layer.setAcceptDrops(True)
        self.txt_curr_layer.setFrame(False)
        self.txt_curr_layer.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_curr_layer.setObjectName("txt_curr_layer")
        self.gridLayout.addWidget(self.txt_curr_layer, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.but_layer_minus = QtWidgets.QPushButton(Dialog)
        self.but_layer_minus.setMaximumSize(QtCore.QSize(20, 16777215))
        self.but_layer_minus.setObjectName("but_layer_minus")
        self.gridLayout.addWidget(self.but_layer_minus, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_poly = QtWidgets.QCheckBox(self.groupBox)
        self.cb_poly.setObjectName("cb_poly")
        self.horizontalLayout.addWidget(self.cb_poly)
        self.cb_hatch = QtWidgets.QCheckBox(self.groupBox)
        self.cb_hatch.setObjectName("cb_hatch")
        self.horizontalLayout.addWidget(self.cb_hatch)
        self.cb_rest = QtWidgets.QCheckBox(self.groupBox)
        self.cb_rest.setObjectName("cb_rest")
        self.horizontalLayout.addWidget(self.cb_rest)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.plotwidget = MplWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotwidget.sizePolicy().hasHeightForWidth())
        self.plotwidget.setSizePolicy(sizePolicy)
        self.plotwidget.setMinimumSize(QtCore.QSize(400, 300))
        self.plotwidget.setObjectName("plotwidget")
        self.verticalLayout_2.addWidget(self.plotwidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.but_layer_plus.setText(_translate("Dialog", "+"))
        self.label.setText(_translate("Dialog", "Layer"))
        self.txt_curr_layer.setInputMask(_translate("Dialog", "9000"))
        self.but_layer_minus.setText(_translate("Dialog", "-"))
        self.groupBox.setTitle(_translate("Dialog", "Plotchoice"))
        self.cb_poly.setText(_translate("Dialog", "Contours"))
        self.cb_hatch.setText(_translate("Dialog", "Hatches"))
        self.cb_rest.setText(_translate("Dialog", "Restpositions"))
from gui.mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
