# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\plotbxyGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.but_load_files = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_load_files.setFont(font)
        self.but_load_files.setObjectName("but_load_files")
        self.horizontalLayout.addWidget(self.but_load_files)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.but_del_entry = QtWidgets.QPushButton(Dialog)
        self.but_del_entry.setObjectName("but_del_entry")
        self.horizontalLayout.addWidget(self.but_del_entry)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.but_plot = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.but_plot.setFont(font)
        self.but_plot.setObjectName("but_plot")
        self.horizontalLayout.addWidget(self.but_plot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lst_files = QtWidgets.QListWidget(Dialog)
        self.lst_files.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lst_files.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lst_files.setObjectName("lst_files")
        self.verticalLayout.addWidget(self.lst_files)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.but_load_files.setText(_translate("Dialog", "Load\n"
"Files"))
        self.but_del_entry.setText(_translate("Dialog", "Delete\n"
"Listentry"))
        self.but_plot.setText(_translate("Dialog", "Plot\n"
".bxy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
